language: "node_js"
node_js:
    - "node"
services:
    - "postgresql"
before_script:
    # - psql -c 'create database teamwork;' -U postgres
    # - psql -f './database/install.sql'
addons:
    postgresql: "10"
    apt:
        packages:
        -   postgresql-10