language: "node_js"
node_js:
    - "node"
services:
    - "postgresql"
before_script:
    - psql -c 'create database teamwork;' -U postgres
addons:
    postgresql: "10"
    apt:
        packages:
        -   postgresql-10